# -*- Makefile -*-

include ${XA_ABSTOPSRCDIR}/mconfig
-include ${XA_ABSTOPSRCDIR}/mconfig.*

obj-m                    += compat_xtables.o

obj-${build_zenset}      += xt_zenset.o
obj-${build_RESET}       += xt_RESET.o

-include ${M}/*.Kbuild
-include ${M}/Kbuild.*
